File to convert all the data.csv files into a readable format and save them in a new folder

In [1]:
import pandas as pd
import numpy as np
import math
import openpyxl

In [ ]:
# Load the raw data
prices_day_minus1 = pd.read_csv("data_old/prices_round_2_day_-1.csv", sep=';')
prices_day_0 = pd.read_csv("data_old/prices_round_2_day_0.csv", sep=';')
prices_day_1 = pd.read_csv("data_old/prices_round_2_day_1.csv", sep=';')
trades_day_minus1 = pd.read_csv("data_old/trades_round_2_day_-1.csv", sep=';')
trades_day_0 = pd.read_csv("data_old/trades_round_2_day_0.csv", sep=';')
trades_day_1 = pd.read_csv("data_old/trades_round_2_day_1.csv", sep=';')

NameError: name 'pd' is not defined

In [ ]:
# trades data does not have a day column, so we add it manually per day
trades_day_minus1["day"] = -1
trades_day_0["day"] = 0
trades_day_1["day"] = 1

# Combine all the trades and prices data into one DataFrame
trades = pd.concat([trades_day_minus1, trades_day_0, trades_day_1], ignore_index=True)
prices = pd.concat([prices_day_minus1, prices_day_0, prices_day_1], ignore_index=True)

In [ ]:
# Add an overall time column to the trades and prices data so that we can distinguish between orders from different days
# The timestamp is in multiples of 100 starting from 0 to 1000000, so we multiply the day by 1000000 and add the timestamp to get a unique time for each order
trades['global_time'] = trades['day'] * 1000000 + trades['timestamp']
# Sort the trades by global time to ensure they are in the correct order
trades.sort_values(by='global_time', inplace=True)

# The prices data has a similar structure, so we do the same for it
prices['global_time'] = prices['day'] * 1000000 + prices['timestamp']
prices.sort_values(by='global_time', inplace=True)

In [5]:
trades.to_excel("data/trades.xlsx", index=False)
prices.to_excel("data/prices.xlsx", index=False)

In [6]:
prices

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss,global_time
0,-1,0,CROISSANTS,4304,112,NaN,NaN,NaN,NaN,4305,112,NaN,NaN,NaN,NaN,4304.5,0.0,-1000000
1,-1,0,JAMS,6670,66,6669.0,137.0,NaN,NaN,6671,66,6672.0,137.0,NaN,NaN,6670.5,0.0,-1000000
2,-1,0,SQUID_INK,2005,1,2002.0,31.0,NaN,NaN,2006,31,NaN,NaN,NaN,NaN,2005.5,0.0,-1000000
3,-1,0,PICNIC_BASKET1,59284,20,59283.0,18.0,NaN,NaN,59294,2,59295.0,36.0,NaN,NaN,59289.0,0.0,-1000000
4,-1,0,PICNIC_BASKET2,30606,20,30605.0,18.0,NaN,NaN,30612,20,30613.0,18.0,NaN,NaN,30609.0,0.0,-1000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239997,1,999900,SQUID_INK,1799,20,NaN,NaN,NaN,NaN,1802,20,NaN,NaN,NaN,NaN,1800.5,0.0,1999900
239992,1,999900,DJEMBES,13419,70,NaN,NaN,NaN,NaN,13420,70,NaN,NaN,NaN,NaN,13419.5,0.0,1999900
239993,1,999900,KELP,2043,20,NaN,NaN,NaN,NaN,2047,20,NaN,NaN,NaN,NaN,2045.0,0.0,1999900
239994,1,999900,CROISSANTS,4266,119,NaN,NaN,NaN,NaN,4267,44,4268.0,75.0,NaN,NaN,4266.5,0.0,1999900
239995,1,999900,JAMS,6519,204,NaN,NaN,NaN,NaN,6521,204,NaN,NaN,NaN,NaN,6520.0,0.0,1999900

In [7]:
trades

,timestamp,buyer,seller,symbol,currency,price,quantity,day,global_time
3,0,NaN,NaN,SQUID_INK,SEASHELLS,2006.0,13,-1,-1000000
4,0,NaN,NaN,SQUID_INK,SEASHELLS,2006.0,1,-1,-1000000
2,0,NaN,NaN,RAINFOREST_RESIN,SEASHELLS,10004.0,1,-1,-1000000
0,0,NaN,NaN,KELP,SEASHELLS,2029.0,13,-1,-1000000
1,0,NaN,NaN,KELP,SEASHELLS,2029.0,1,-1,-1000000
...,...,...,...,...,...,...,...,...,...
37873,999500,NaN,NaN,SQUID_INK,SEASHELLS,1802.0,1,1,1999500
37874,999600,NaN,NaN,KELP,SEASHELLS,2046.0,2,1,1999600
37875,999700,NaN,NaN,CROISSANTS,SEASHELLS,4269.0,5,1,1999700
37876,999700,NaN,NaN,KELP,SEASHELLS,2044.0,1,1,1999700
37877,999700,NaN,NaN,SQUID_INK,SEASHELLS,1800.0,1,1,1999700

In [8]:
print(prices_day_minus1.info())
print(prices_day_0.info())
print(prices_day_1.info())
print(prices.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              80000 non-null  int64
 1   timestamp        80000 non-null  int64
 2   product          80000 non-null  object
 3   bid_price_1      80000 non-null  int64
 4   bid_volume_1     80000 non-null  int64
 5   bid_price_2      36637 non-null  float64
 6   bid_volume_2     36637 non-null  float64
 7   bid_price_3      7838 non-null   float64
 8   bid_volume_3     7838 non-null   float64
 9   ask_price_1      80000 non-null  int64
 10  ask_volume_1     80000 non-null  int64
 11  ask_price_2      37520 non-null  float64
 12  ask_volume_2     37520 non-null  float64
 13  ask_price_3      7898 non-null   float64
 14  ask_volume_3     7898 non-null   float64
 15  mid_price        80000 non-null  float64
 16  profit_and_loss  80000 non-null  float64
dtypes: float64(10), int64(6), object(1)
memory usage: 10.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              80000 non-null  int64
 1   timestamp        80000 non-null  int64
 2   product          80000 non-null  object
 3   bid_price_1      80000 non-null  int64
 4   bid_volume_1     80000 non-null  int64
 5   bid_price_2      36689 non-null  float64
 6   bid_volume_2     36689 non-null  float64
 7   bid_price_3      7825 non-null   float64
 8   bid_volume_3     7825 non-null   float64
 9   ask_price_1      80000 non-null  int64
 10  ask_volume_1     80000 non-null  int64
 11  ask_price_2      37608 non-null  float64
 12  ask_volume_2     37608 non-null  float64
 13  ask_price_3      7851 non-null   float64
 14  ask_volume_3     7851 non-null   float64
 15  mid_price        80000 non-null  float64
 16  profit_and_loss  80000 non-null  float64
dtypes: float64(10), int64(6), object(1)
memory usage: 10.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              80000 non-null  int64
 1   timestamp        80000 non-null  int64
 2   product          80000 non-null  object
 3   bid_price_1      80000 non-null  int64
 4   bid_volume_1     80000 non-null  int64
 5   bid_price_2      36462 non-null  float64
 6   bid_volume_2     36462 non-null  float64
 7   bid_price_3      7844 non-null   float64
 8   bid_volume_3     7844 non-null   float64
 9   ask_price_1      80000 non-null  int64
 10  ask_volume_1     80000 non-null  int64
 11  ask_price_2      37484 non-null  float64
 12  ask_volume_2     37484 non-null  float64
 13  ask_price_3      7836 non-null   float64
 14  ask_volume_3     7836 non-null   float64
 15  mid_price        80000 non-null  float64
 16  profit_and_loss  80000 non-null  float64
dtypes: float64(10), int64(6), object(1)
memory usage: 10.4+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 240000 entries, 0 to 239995
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   day              240000 non-null  int64
 1   timestamp        240000 non-null  int64
 2   product          240000 non-null  object
 3   bid_price_1      240000 non-null  int64
 4   bid_volume_1     240000 non-null  int64
 5   bid_price_2      109788 non-null  float64
 6   bid_volume_2     109788 non-null  float64
 7   bid_price_3      23507 non-null   float64
 8   bid_volume_3     23507 non-null   float64
 9   ask_price_1      240000 non-null  int64
 10  ask_volume_1     240000 non-null  int64
 11  ask_price_2      112612 non-null  float64
 12  ask_volume_2     112612 non-null  float64
 13  ask_price_3      23585 non-null   float64
 14  ask_volume_3     23585 non-null   float64
 15  mid_price        240000 non-null  float64
 16  profit_and_loss  240000 non-null  float64
 17  global_time      240000 non-null  int64
dtypes: float64(10), int64(7), object(1)
memory usage: 34.8+ MB
None

In [9]:
print(trades_day_minus1.info())
print(trades_day_0.info())
print(trades_day_1.info())
print(trades.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12620 entries, 0 to 12619
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  12620 non-null  int64
 1   buyer      0 non-null      float64
 2   seller     0 non-null      float64
 3   symbol     12620 non-null  object
 4   currency   12620 non-null  object
 5   price      12620 non-null  float64
 6   quantity   12620 non-null  int64
 7   day        12620 non-null  int64
dtypes: float64(3), int64(3), object(2)
memory usage: 788.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12576 entries, 0 to 12575
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  12576 non-null  int64
 1   buyer      0 non-null      float64
 2   seller     0 non-null      float64
 3   symbol     12576 non-null  object
 4   currency   12576 non-null  object
 5   price      12576 non-null  float64
 6   quantity   12576 non-null  int64
 7   day        12576 non-null  int64
dtypes: float64(3), int64(3), object(2)
memory usage: 786.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12682 entries, 0 to 12681
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  12682 non-null  int64
 1   buyer      0 non-null      float64
 2   seller     0 non-null      float64
 3   symbol     12682 non-null  object
 4   currency   12682 non-null  object
 5   price      12682 non-null  float64
 6   quantity   12682 non-null  int64
 7   day        12682 non-null  int64
dtypes: float64(3), int64(3), object(2)
memory usage: 792.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 37878 entries, 3 to 37877
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    37878 non-null  int64
 1   buyer        0 non-null      float64
 2   seller       0 non-null      float64
 3   symbol       37878 non-null  object
 4   currency     37878 non-null  object
 5   price        37878 non-null  float64
 6   quantity     37878 non-null  int64
 7   day          37878 non-null  int64
 8   global_time  37878 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.9+ MB
None