File to convert all the data.csv files into a readable format and save them in a new folder

In [1]:
import pandas as pd
import numpy as np
import math
import openpyxl

In [3]:
# Load the raw data
prices_day_minus2 = pd.read_csv("data_old/prices_round_1_day_-2.csv", sep=';')
prices_day_minus1 = pd.read_csv("data_old/prices_round_1_day_-1.csv", sep=';')
prices_day_0 = pd.read_csv("data_old/prices_round_1_day_0.csv", sep=';')
trades_day_minus2 = pd.read_csv("data_old/trades_round_1_day_-2.csv", sep=';')
trades_day_minus1 = pd.read_csv("data_old/trades_round_1_day_-1.csv", sep=';')
trades_day_0 = pd.read_csv("data_old/trades_round_1_day_0.csv", sep=';')

In [4]:
# trades data does not have a day column, so we add it manually per day
trades_day_minus2["day"] = -2
trades_day_minus1["day"] = -1
trades_day_0["day"] = 0

# Combine all the trades and prices data into one DataFrame
trades = pd.concat([trades_day_minus2, trades_day_minus2, trades_day_0], ignore_index=True)
prices = pd.concat([prices_day_minus2, prices_day_minus1, prices_day_0], ignore_index=True)

In [5]:
# Add an overall time column to the trades and prices data so that we can distinguish between orders from different days
# The timestamp is in multiples of 100 starting from 0 to 1000000, so we multiply the day by 1000000 and add the timestamp to get a unique time for each order
trades['global_time'] = trades['day'] * 1000000 + trades['timestamp']
# Sort the trades by global time to ensure they are in the correct order
trades.sort_values(by='global_time', inplace=True)

# The prices data has a similar structure, so we do the same for it
prices['global_time'] = prices['day'] * 1000000 + prices['timestamp']
prices.sort_values(by='global_time', inplace=True)

In [6]:
trades.to_excel("data/trades.xlsx", index=False)
prices.to_excel("data/prices.xlsx", index=False)

In [7]:
prices

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss,global_time
0,-2,0,RAINFOREST_RESIN,9996,1,9995.0,25.0,NaN,NaN,10004,1,10005.0,25.0,NaN,NaN,10000.0,0.0,-2000000
1,-2,0,KELP,1998,26,NaN,NaN,NaN,NaN,2002,26,NaN,NaN,NaN,NaN,2000.0,0.0,-2000000
2,-2,0,SQUID_INK,1998,26,NaN,NaN,NaN,NaN,2002,26,NaN,NaN,NaN,NaN,2000.0,0.0,-2000000
3,-2,100,SQUID_INK,1999,5,1998.0,26.0,NaN,NaN,2001,20,NaN,NaN,NaN,NaN,2000.0,0.0,-1999900
5,-2,100,KELP,2000,5,1999.0,6.0,1998.0,20.0,2002,20,NaN,NaN,NaN,NaN,2001.0,0.0,-1999900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89996,0,999800,RAINFOREST_RESIN,9995,27,NaN,NaN,NaN,NaN,10005,27,NaN,NaN,NaN,NaN,10000.0,0.0,999800
89994,0,999800,SQUID_INK,1837,27,NaN,NaN,NaN,NaN,1839,1,1840.0,27.0,NaN,NaN,1838.0,0.0,999800
89999,0,999900,KELP,2032,23,NaN,NaN,NaN,NaN,2035,23,NaN,NaN,NaN,NaN,2033.5,0.0,999900
89998,0,999900,SQUID_INK,1838,23,NaN,NaN,NaN,NaN,1841,23,NaN,NaN,NaN,NaN,1839.5,0.0,999900
89997,0,999900,RAINFOREST_RESIN,9996,2,9995.0,21.0,NaN,NaN,10004,2,10005.0,21.0,NaN,NaN,10000.0,0.0,999900

In [8]:
trades

,timestamp,buyer,seller,symbol,currency,price,quantity,day,global_time
0,0,NaN,NaN,KELP,SEASHELLS,2002.0,1,-2,-2000000
1,0,NaN,NaN,RAINFOREST_RESIN,SEASHELLS,9996.0,1,-2,-2000000
8400,0,NaN,NaN,RAINFOREST_RESIN,SEASHELLS,9996.0,1,-2,-2000000
8401,0,NaN,NaN,SQUID_INK,SEASHELLS,2002.0,1,-2,-2000000
8398,0,NaN,NaN,KELP,SEASHELLS,2002.0,1,-2,-2000000
...,...,...,...,...,...,...,...,...,...
24973,999500,NaN,NaN,KELP,SEASHELLS,2032.0,2,0,999500
24974,999500,NaN,NaN,RAINFOREST_RESIN,SEASHELLS,9995.0,2,0,999500
24975,999500,NaN,NaN,SQUID_INK,SEASHELLS,1830.0,2,0,999500
24977,999600,NaN,NaN,SQUID_INK,SEASHELLS,1832.0,1,0,999600
24976,999600,NaN,NaN,KELP,SEASHELLS,2032.0,1,0,999600

In [9]:
print(prices_day_minus2.info())
print(prices_day_minus2.info())
print(prices_day_0.info())
print(prices.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              30000 non-null  int64
 1   timestamp        30000 non-null  int64
 2   product          30000 non-null  object
 3   bid_price_1      30000 non-null  int64
 4   bid_volume_1     30000 non-null  int64
 5   bid_price_2      11790 non-null  float64
 6   bid_volume_2     11790 non-null  float64
 7   bid_price_3      2081 non-null   float64
 8   bid_volume_3     2081 non-null   float64
 9   ask_price_1      30000 non-null  int64
 10  ask_volume_1     30000 non-null  int64
 11  ask_price_2      12619 non-null  float64
 12  ask_volume_2     12619 non-null  float64
 13  ask_price_3      2193 non-null   float64
 14  ask_volume_3     2193 non-null   float64
 15  mid_price        30000 non-null  float64
 16  profit_and_loss  30000 non-null  float64
dtypes: float64(10), int64(6), object(1)
memory usage: 3.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              30000 non-null  int64
 1   timestamp        30000 non-null  int64
 2   product          30000 non-null  object
 3   bid_price_1      30000 non-null  int64
 4   bid_volume_1     30000 non-null  int64
 5   bid_price_2      11790 non-null  float64
 6   bid_volume_2     11790 non-null  float64
 7   bid_price_3      2081 non-null   float64
 8   bid_volume_3     2081 non-null   float64
 9   ask_price_1      30000 non-null  int64
 10  ask_volume_1     30000 non-null  int64
 11  ask_price_2      12619 non-null  float64
 12  ask_volume_2     12619 non-null  float64
 13  ask_price_3      2193 non-null   float64
 14  ask_volume_3     2193 non-null   float64
 15  mid_price        30000 non-null  float64
 16  profit_and_loss  30000 non-null  float64
dtypes: float64(10), int64(6), object(1)
memory usage: 3.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              30000 non-null  int64
 1   timestamp        30000 non-null  int64
 2   product          30000 non-null  object
 3   bid_price_1      30000 non-null  int64
 4   bid_volume_1     30000 non-null  int64
 5   bid_price_2      11733 non-null  float64
 6   bid_volume_2     11733 non-null  float64
 7   bid_price_3      2031 non-null   float64
 8   bid_volume_3     2031 non-null   float64
 9   ask_price_1      30000 non-null  int64
 10  ask_volume_1     30000 non-null  int64
 11  ask_price_2      12518 non-null  float64
 12  ask_volume_2     12518 non-null  float64
 13  ask_price_3      2115 non-null   float64
 14  ask_volume_3     2115 non-null   float64
 15  mid_price        30000 non-null  float64
 16  profit_and_loss  30000 non-null  float64
dtypes: float64(10), int64(6), object(1)
memory usage: 3.9+ MB
None
<class 'pandas.core.frame.DataFrame'>
Index: 90000 entries, 0 to 89997
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   day              90000 non-null  int64
 1   timestamp        90000 non-null  int64
 2   product          90000 non-null  object
 3   bid_price_1      90000 non-null  int64
 4   bid_volume_1     90000 non-null  int64
 5   bid_price_2      35222 non-null  float64
 6   bid_volume_2     35222 non-null  float64
 7   bid_price_3      6130 non-null   float64
 8   bid_volume_3     6130 non-null   float64
 9   ask_price_1      90000 non-null  int64
 10  ask_volume_1     90000 non-null  int64
 11  ask_price_2      37565 non-null  float64
 12  ask_volume_2     37565 non-null  float64
 13  ask_price_3      6415 non-null   float64
 14  ask_volume_3     6415 non-null   float64
 15  mid_price        90000 non-null  float64
 16  profit_and_loss  90000 non-null  float64
 17  global_time      90000 non-null  int64
dtypes: float64(10), int64(7), object(1)
memory usage: 13.0+ MB
None

In [10]:
print(trades_day_minus2.info())
print(trades_day_minus2.info())
print(trades_day_0.info())
print(trades.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8398 entries, 0 to 8397
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  8398 non-null   int64
 1   buyer      0 non-null      float64
 2   seller     0 non-null      float64
 3   symbol     8398 non-null   object
 4   currency   8398 non-null   object
 5   price      8398 non-null   float64
 6   quantity   8398 non-null   int64
 7   day        8398 non-null   int64
dtypes: float64(3), int64(3), object(2)
memory usage: 525.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8398 entries, 0 to 8397
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  8398 non-null   int64
 1   buyer      0 non-null      float64
 2   seller     0 non-null      float64
 3   symbol     8398 non-null   object
 4   currency   8398 non-null   object
 5   price      8398 non-null   float64
 6   quantity   8398 non-null   int64
 7   day        8398 non-null   int64
dtypes: float64(3), int64(3), object(2)
memory usage: 525.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8182 entries, 0 to 8181
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   timestamp  8182 non-null   int64
 1   buyer      0 non-null      float64
 2   seller     0 non-null      float64
 3   symbol     8182 non-null   object
 4   currency   8182 non-null   object
 5   price      8182 non-null   float64
 6   quantity   8182 non-null   int64
 7   day        8182 non-null   int64
dtypes: float64(3), int64(3), object(2)
memory usage: 511.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 24978 entries, 0 to 24976
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    24978 non-null  int64
 1   buyer        0 non-null      float64
 2   seller       0 non-null      float64
 3   symbol       24978 non-null  object
 4   currency     24978 non-null  object
 5   price        24978 non-null  float64
 6   quantity     24978 non-null  int64
 7   day          24978 non-null  int64
 8   global_time  24978 non-null  int64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.9+ MB
None